services:
  web:
    environment:
      - PORT:${PORT}
      - MESSAGE:${MESSAGE}
    env_file:
     - path: ./default.env
       required: true # default
    build:
      context: ./node-app
    ports:
      - "3000:${PORT}"
     