services:
  web:
    container_name: ${container_name}
    build:
      context: ./node-app
    ports:
      - "3000:${PORT}"
     
## Run this command  sudo docker-compose --env-file ./node-app/.env up --build