services:
  web:
    env_file:
      - path: ./node-app/.env
        required: true # default
    container_name: ${container_name}
    build:
      context: ./node-app
    ports:
      - "3000:${PORT}"
      
## You need to use .env file in folder where docker-compose.yaml is in order to declaring default environment variables for both docker-compose.yaml file and docker container. env_file section is used to put values into container only.
