services:
  web:
    environment:
      - PORT:${PORT}
      - MESSAGE:`Hello`
    build:
      context: ./node-app
      args:
        - PORT=${PORT}
    ports:
      - "3000:${PORT}"
    env_file:
      - ./.env

## Either environment: will be used or env_file and they are used put values to dockerfile for its container.
