services:
  web:
    environment:
      - PORT:${PORT}
      - MESSAGE:${MESSAGE}
    build:
      context: ./node-app
      args:
        - PORT=${PORT}
    ports:
      - "3000:${PORT}"
    env_file:
      - ./.env
